{% set name = "virtualship" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virtualship-{{ version }}.tar.gz
  sha256: 2d5b812136d4e267258abc5b0425cca7807de6e8cbd6b367d8326a6be537c586

build:
  entry_points:
    - virtualship = virtualship.cli.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - click
    - parcels >3, <3.1.0
    - pyproj >=3,<4
    - sortedcontainers ==2.4.0
    - opensimplex ==0.4.5
    - numpy >=1,<2
    - pydantic >=2,<3

test:
  imports:
    - virtualship
  commands:
    - pip check
    - virtualship --help
  requires:
    - pip

about:
  home: https://github.com/OceanParcels/virtualship
  summary: Code for the Virtual Ship Classroom, where Marine Scientists can combine Copernicus Marine Data with an OceanParcels ship to go on a virtual expedition.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ammedd
    - erikvansebille
    - VeckoTheGecko
